### PR TITLE
Fix bug of copy the same file with pai-fs

### PR DESCRIPTION
**Pull request by xiaoxinla**
delete the file if we find it has already exist in the path, and then continue the copy process.

### CODE REVIEW

**Comment by fanyangCS** [comment]
@sterowang is added to the review. #Closed

**Comment by fanyangCS** [comment]
@abuccts is added to the review. #Closed

**Comment by abuccts** [comment]
#247 is caused by hdfs instead of pai-fs and it can not be reproduce now.
It seems that `pai-fs.py -cp -r` called `cp_file` instead of `remote_cp_file`.

**Comment by xiaoxinla** [comment]
@abuccts I have tested the code of cp_file, it called remote_cp actually. How do you test the case?

**Comment by xiaoxinla** [comment]
@fanyangCS @abuccts @sterowang Can you merge it into master?

**Pull request merged**
