### PR TITLE
add more node related alerts

### PR DESCRIPTION
**Pull request by xudifsd**

### CODE REVIEW

**Comment by fanyangCS** [comment]
I remember we already have alert for memory pressure?

**Comment by xudifsd** [comment]
Oh, yes, it subtract total memory with used from node-exporter, newly added memory_pressure is kubernetes defined. May duplicated. Which one to use?

**Comment by fanyangCS** [comment]
we use our own. k8s cannot modify job containers.

**Comment by xudifsd** [comment]
ok, removed k8s one

**Comment by xudifsd** [comment]
@fanyangCS please approve this if appropriate.

**Pull request merged**
