### PR TITLE
[Drivers] Make drivers version configurable

### PR DESCRIPTION
**Pull request by ydye**

### CODE REVIEW

**Comment by ydye** [comment]
@wangcan0329 Done

**Comment by fanyangCS** [comment]
shall we add a document to explain how to change driver version?

**Comment by ydye** [comment]
@fanyangCS 
Add some notification in the cluster configuration https://github.com/Microsoft/pai/blob/3d03ce34be82b5a8009228cf6c07bdcc58bbf1b0/examples/cluster-configuration/services-configuration.yaml#L103

I prefer to write more concrete document after the developing of cluster object model

**Comment by ydye** [comment]
@fanyangCS   The document is added in another PR. https://github.com/Microsoft/pai/pull/1632

**Pull request merged**
