### PR TITLE
[REST server]Use framework name as job name

### LINKED ISSUE #2439: Use framework name as job name in REST server / web portal.
Since enabling ACL in framework launcher, the _framework name_ in framework launcher are prepended the user name to avoid the naming confliction, looks like `user~job`. For backward compatibility, user-faced services like REST server & web portal chose to hide these details to user, still returns & shows _job name_, w/o user name prepended. As more services, plugins & third-party tools integrate to rest server/web portal, the difference between _job name_ (without the username, `job`) and _framework name_ (with the username, `user~job`) causes confusing and extra workload. To clarify, the meaning of _job name_ terminology will be changed to the same as _framework name_, which is prepended username, looks like `user~job`, and still provided the backward compatibility of the _job name_ without the username.

### PR DESCRIPTION
**Pull request by Gerhut**
Closes #2439 

# This is a (theoretical) compatible API change, includes:

## Deprecated `/user/:user/jobs`-family APIs

Rewrite them to `/jobs/:user~:jobname`-family.

<a name="tip">*</a>: If a namespace is already provided in job name, the `:user` param will be ignored, this is for e2e compatibility: a job created by `POST /user/:user/jobs` with un-namespaced job name would be able to retrieved by the following ways:

1. `GET /user/:user/jobs/:jobname`: client may hard coded the job name.
2. `GET /user/:user/jobs/:user~:jobname`: client may retrieve the job name from creating response.
3. `GET /jobs/:user~:jobname`: the new recommended way.

### Rewrite `/user/:user/jobs` as `/jobs?username=:user`

Including `GET` and `POST` requests.

The `POST` one is newly added for distinguish with legacy (pre-0.7.0) `POST /jobs` API

- If `POST /jobs` with **un-namespaced** job name is called, the legacy (pre-0.7.0) job without namespace will be created. This is the compatible way to create a legacy job and have no change.
- If `POST /jobs?username=:user` with **un-namespaced** job name is called, the modern job `:user~:jobname` will be created, which is rewritten from `POST /user/:user/jobs` for compatibility with current version.
- If `POST /jobs` with **namespaced** job name is called, the modern job `:jobname` will be created, which is the recommended way.
- If `POST /jobs?username=:user` with **namespaced** job name is called, the user query is ignored, see [*](#tip)

### Rewrite `/user/:user/jobs/:job` as `/jobs/:user~:job`

Including `GET`, `PUT`, `DELETE` (undocumented API)

### Rewrite `/user/:user1/jobs/:user2~:job` as `/jobs/:user2~:job`

Including `GET`, `PUT`, `DELETE` (undocumented API), See [*](#tip)

### Rewrite `/user/:user/jobs/:job/*` as `/jobs/:user~:job/*`

Including `GET`, `PUT`

### Rewrite `/user/:user1/jobs/:user2~:job/*` as `/jobs/:user2~:job/*`

Including `GET`, `PUT`, See [*](#tip)

## There will be no namespace-wiper in the job responses

Previously, if the job name includes "~", to compatible with pre-0.7.0 legacy job, the namespace will be wiped, which makes the job name in rest-server / webportal differs with other services, now it will not be wiped automatically.

### CODE REVIEW

**Comment by scarlett2018** [comment]
@Gerhut  - is there any impact to client side like NNI and VS code extension?

**Comment by Gerhut** [comment]
> @Gerhut  - is there any impact to client side like NNI and VS code extension?

Theoretically, all API changes are design to be compatible with current version as well as pre-0.7.0 version

**Comment by SparkSnail** [comment]
Does PUT method of `user/:user/jobs/:jobName/executionType` still works?

**Comment by scarlett2018** [comment]
> > @Gerhut  - is there any impact to client side like NNI and VS code extension?
> 
> Theoretically, all API changes are design to be compatible with current version as well as pre-0.7.0 version

@Gerhut Sounds good, I just created an issue for adding few test cases for current client dependency scenarios. #2616  To make sure any changes we made had been evaluated by these test cases before release. 

@yds05  @sunqinzheng  @sotetsuk - need your helps to outlist all the test cases that are impacting your integration, thanks.

**Comment by Gerhut** [comment]
> Does PUT method of user/:user/jobs/:jobName/executionType still works?

Sure, it will be rewritten as `/jobs/:user~:jobName/executionType` and act as it was

You could view the test case of this PR and found that few changes.

**Comment by sotetsuk** [comment]
I'll check the dependency to my client (https://github.com/sotetsuk/paicli) in this weekend.
But there is no need to wait my response. I'll fix soon after the release if there is a problem. Thanks.

**Pull request merged**
