### PR TITLE
do not emit invalid gpu metrics if gpu not supported by nvidia-smi

### LINKED ISSUE #949: gpu_exporter.prom: text format parsing error in line 2: expected float as value, got \"N/A\"
After the pai is installed, the node information except for GPU is available.  here is the node-exported log information. 
```
time="2018-07-21T02:18:10Z" level=info msg="Starting node_exporter (version=0.15.2, branch=HEAD, revision=98bc64930d34878b84a0f87dfe6e1a6da61e532d)" source="node_exporter.go:43"
time="2018-07-21T02:18:10Z" level=info msg="Build context (go=go1.9.2, user=root@d5c4792c921f, date=20171205-14:50:53)" source="node_exporter.go:44"
time="2018-07-21T02:18:10Z" level=info msg="Enabled collectors:" source="node_exporter.go:50"
time="2018-07-21T02:18:10Z" level=info msg=" - stat" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - filefd" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - cpu" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - loadavg" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - uname" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - diskstats" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - mdadm" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - meminfo" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - textfile" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - netdev" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - filesystem" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - bcache" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - sockstat" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - conntrack" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - ipvs" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - time" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - hwmon" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - netstat" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg=" - timex" source="node_exporter.go:52"
time="2018-07-21T02:18:10Z" level=info msg="Listening on :9100" source="node_exporter.go:76"
time="2018-07-21T02:18:45Z" level=error msg="Error parsing /datastorage/prometheus/gpu_exporter.prom: text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:99"
time="2018-07-21T02:19:15Z" level=error msg="Error parsing /datastorage/prometheus/gpu_exporter.prom: text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:99"
time="2018-07-21T02:19:45Z" level=error msg="Error parsing /datastorage/prometheus/gpu_exporter.prom: text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:99"
time="2018-07-21T02:20:15Z" level=error msg="Error parsing /datastorage/prometheus/gpu_exporter.prom: text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:99"
```
Besides, access to web portal, the GPU count is "N/A"and GPU utilization and GPU memory is "no data points"

webportal

### PR DESCRIPTION
**Pull request by xudifsd**
fix #949

### CODE REVIEW

**Comment by DengZeshuai** [comment]
It is kind of embarrassing, I download the code of branch `master` , and I try to rebuild the cluster. This time, not only it cannot show the information of GPU, but also it cannot show the information of other devices. Here is the result of webportal access `http://<masterip>:9286`
result

And this  is the logs of node-exporter, it is the similar with the logs before.
```
time="2018-07-25T06:08:36Z" level=info msg="Starting node_exporter (version=0.16.0, branch=HEAD, revision=d42bd70f4363dced6b77d8fc311ea57b63387e4f)" source="node_exporter.go:82"
time="2018-07-25T06:08:36Z" level=info msg="Build context (go=go1.9.6, user=root@a67a9bc13a69, date=20180515-15:52:42)" source="node_exporter.go:83"
time="2018-07-25T06:08:36Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2018-07-25T06:08:36Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2018-07-25T06:08:36Z" level=info msg="Listening on :9100" source="node_exporter.go:111"
time="2018-07-25T06:08:46Z" level=error msg="Error parsing \"/datastorage/prometheus/gpu_exporter.prom\": text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:212"
time="2018-07-25T06:09:16Z" level=error msg="Error parsing \"/datastorage/prometheus/gpu_exporter.prom\": text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:212"
time="2018-07-25T06:09:16Z" level=error msg="Error parsing \"/datastorage/prometheus/gpu_exporter.prom\": text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:212"
time="2018-07-25T06:09:46Z" level=error msg="Error parsing \"/datastorage/prometheus/gpu_exporter.prom\": text format parsing error in line 2: expected float as value, got \"N/A\"" source="textfile.go:212"
....
```

**Comment by xudifsd** [comment]
@DengZeshuai we also found cpu/memory's issue, that's because:

Node_exporter introduced some break changes in [0.16 release](https://github.com/prometheus/node_exporter/releases/tag/v0.16.0), which changed metrics node_cpu into node_cpu_seconds_total. But our Grafana still using node_cpu.

Whereas memory, our Grafana uses `node_memory_Mem{Total, Free}` while node_exporter exports as `node_memory_Mem{Total, Free}_bytes` which is also due to break changes.

Disk is also due to break changes.

Network is due to disabled `--no-collector.netdev`, which is due to [this](https://github.com/Microsoft/pai/pull/882/files#diff-d3936bba012f9f46357f2a2e7c8220aaR72) commit.

For gpu problem, did you push what you built for `master`'s `gpu-exporter`?

**Comment by DengZeshuai** [comment]
Thanks for you explanation. And I did not push my built for ` master`'s `gpu-exporter`, I just removed the old pai folder of container `dev-box` and git clone branch `master` into this container and then rebuild the cluster. @xudifsd

**Comment by xudifsd** [comment]
#987 will fix problems due to node_exporter rename.

Sorry for inconvenience, we should add more tests.

For gpu-exporter, you have to rebuild and push the image before redeploy.
```
./paictl.py image build -p /path/to/cluster/config -n gpu-exporter
./paictl.py image push -p /path/to/cluster/config -n gpu-exporter
./paictl.py service stop -p /path/to/cluster/config -n prometheus
./paictl.py service start -p /path/to/cluster/config -n prometheus
```

**Pull request merged**
