### PR TITLE
Fix version change in webportal

### PR DESCRIPTION
**Pull request by hzy46**
Currently we use `cp -arf "../../../version" "../version"` to copy the PAI version to `src/webportal/` , here is a small problem:

- If it is the first time to run `cp -arf "../../../version" "../version"` , a `version` folder will be created under `src/webportal`
- If you run the  `cp -arf "../../../version" "../version"` again,  it will copy the `version` folder under `src/webportal/version/`. Thus the folder structure becomes `src/webportal/version/version`, which is not desired.

To reproduce:
- build and deploy the cluster
- change the PAI.VERSION to make a new version
- build and deploy the cluster, but the version will not change in webportal

### CODE REVIEW

**Comment by debuggy** [comment]
Why would this ```cp``` command run two times?

**Comment by hzy46** [comment]
> Why would this `cp` command run two times?

For example, I built and deployed the cluster on 2pm. After some code changes, I built it again on 3pm using the same directory. Then this problem would occurred.

**Comment by debuggy** [comment]
> 
> 
> > Why would this `cp` command run two times?
> 
> For example, I built and deployed the cluster on 2pm. After some code changes, I built it again on 3pm using the same directory. Then this problem would occur.

ok, I got it.

**Comment by hzy46** [comment]
The way in the script to make a "version" folder seems to conflict with the Jenkins pipeline. Close this PR to find a better fix or modify the Jenkins file.

**Pull request closed without merging**
