### PR TITLE
Fix bugs in pure k8s

### PR DESCRIPTION
**Pull request by abuccts**
* ignore modified files during deployment in git
* fix typo `retryPolicy` -> `retryPolicyStatus`
* fix incompatible default task role name
* rename "Go to Yarn Tracking Page"
* convert task role names in log path
* change `alert` to `prompt` in view token

### CODE REVIEW

**Comment by mzmssg** [comment]
Change the prefix to a legal name? https://github.com/microsoft/pai/blob/19817a0170b72d44ed9ce0fe2fe6f430c0d5b3f3/src/webportal/src/app/job-submission/components/task-roles.jsx#L11

**Comment by mzmssg** [comment]
By the way, why not change restserver validation?

**Comment by abuccts** [comment]
> By the way, why not change restserver validation?

Why need to change validation? The previous name still works.

**Comment by mzmssg** [comment]
> fix incompatible default task role name

Not sure your `still works`. If it works, why we need to fix the incompatibility?

**Pull request merged**
