### PR TITLE
Fix cntk test exit code

### PR DESCRIPTION
**Pull request by mzmssg**

### CODE REVIEW

**Comment by xudifsd** [comment]
maybe `set -e`? could `hdfs-mount` also go wrong?

**Comment by mzmssg** [comment]
@xudifsd This tool is not that stable, sometimes it will enter zombie and block exit. I'm afraid that `set -e` will confuse us with this tool's bug.

**Comment by xudifsd** [comment]
if `set -e` could expose this tools' bugs then we can fix them, instead of hide and pretend it's fine.

**Comment by fanyangCS** [comment]
we should remove this test. we do not encourage user to use hdfs-mount

**Comment by mzmssg** [comment]
closed for test removed

**Pull request closed without merging**
