### PR TITLE
[CI] Use nightly-build status in README.md

### PR DESCRIPTION
**Pull request by yiyione**
Old:
[Build Status](https://github.com/microsoft/pai/actions)

New:
[Build Status](https://openpai.visualstudio.com/OpenPAI/_build/latest?definitionId=25&branchName=master)

### CODE REVIEW

**Comment by hzy46** [comment]
Will it be visible to those who are outside Microsoft's network?

**Comment by yiyione** [comment]
> Will it be visible to those who are outside Microsoft's network?

Looks OK on my mobile phone without login github/azure.

**Review by debuggy — APPROVED** [review]

**Comment by hzy46** [comment]
Please also change https://github.com/microsoft/pai/blob/master/docs/index.md and https://github.com/microsoft/pai/blob/master/docs_zh_CN/index.md , thanks

**Comment by yiyione** [comment]
> Please also change https://github.com/microsoft/pai/blob/master/docs/index.md and https://github.com/microsoft/pai/blob/master/docs_zh_CN/index.md , thanks

Done.

**Pull request merged**
