### PR TITLE
Fix tag auth

### PR DESCRIPTION
**Pull request by hzy46**
Make a user can add/delete tags to his/her own jobs.

### CODE REVIEW

**Review by suiguoxin — COMMENTED** [review]
Change the auth of `deleteTag` together with `addTag` ?

**Comment by hzy46** [comment]
> Change the auth of `deleteTag` together with `addTag` ?

Done.

**Comment by suiguoxin** [comment]
> > Change the auth of `deleteTag` together with `addTag` ?
> 
> Done.

Remember to remove 

> > Change the auth of `deleteTag` together with `addTag` ?
> 
> Done.

Remember to remove `checkAdmin` middleware from deleteTag route.

**Comment by hzy46** [comment]
> > > Change the auth of `deleteTag` together with `addTag` ?
> > 
> > 
> > Done.
> 
> Remember to remove `checkAdmin` middleware from deleteTag route.

Done.

**Review by suiguoxin — APPROVED** [review]

**Pull request merged**
