### PR TITLE
Remove unnecessary volume of docker root dir in pai's service

### PR DESCRIPTION
**Pull request by ydye**

### CODE REVIEW

**Comment by hao1939** [comment]
@ydye , per my understanding, after this change, we still don't support customized docker config?
For example, if user made the docker config below (see the #781), PAI would fail.
```
~$ cat /etc/docker/daemon.json
{
  "graph": "/mnt/var/lib/docker"
}

```

**Comment by xudifsd** [comment]
ok for node-exporter removal.

**Comment by ydye** [comment]
@mzmssg please check this pr, to ensure whether this change will have a side effect on your work.

**Comment by mzmssg** [comment]
@ydye You can remove it first, I will test and add it back if it's necessary for docker executor.

**Pull request merged**
