### PR TITLE
fix get job api slow response issue

### PR DESCRIPTION
**Pull request by suiguoxin**

### CODE REVIEW

**Comment by yqwang-ms** [comment]
@Binyang2014  @debuggy who ever touched the code to review

**Comment by Binyang2014** [comment]
@suiguoxin Can you provide some performance test results after this fix?

**Comment by suiguoxin** [comment]
> @suiguoxin Can you provide some performance test results after this fix?

I test with the same job. The time needed for `convertTaskDetail` function is decreased from 4~5s to 100-200ms, which is the same as in previous version.

**Comment by suiguoxin** [comment]
The performance test result is recorded in https://github.com/microsoft/pai/issues/5012. @Binyang2014 @yqwang-ms

**Review by yqwang-ms — APPROVED** [review]

**Pull request merged**
