### PR TITLE
Move GPU device plugin to service

### PR DESCRIPTION
**Pull request by abuccts**
Move GPU device plugin to service.

### CODE REVIEW

**Comment by fanyangCS** [comment]
if there is a way to bypass some Plugins during deployment?

**Comment by abuccts** [comment]
> if there is a way to bypass some Plugins during deployment?

we can add a configuration section, but the device plugin pod won't effect if it is deployed to a node without certain device

**Comment by yqwang-ms** [comment]
We need to define whether **stop** PAI services should have impacts on running jobs. 
(Currently stop FC will have no impacts on exist running, but delete FC will delete running jobs)
Seems current stop for device plugin will impact?

**Comment by abuccts** [comment]
> We need to define whether **stop** PAI services should have impacts on running jobs.
> (Currently stop FC will have no impacts on exist running, but delete FC will delete running jobs)
> Seems current stop for device plugin will impact?

moved to `delete.sh`

**Comment by yqwang-ms** [comment]
> We need to define whether **stop** PAI services should have impacts on running jobs.
> (Currently stop FC will have no impacts on exist running, but delete FC will delete running jobs)
> Seems current stop for device plugin will impact?

@fanyangCS what is the expected behaiour for stop PAI services:

**Comment by fanyangCS** [comment]
> > We need to define whether **stop** PAI services should have impacts on running jobs.
> > (Currently stop FC will have no impacts on exist running, but delete FC will delete running jobs)
> > Seems current stop for device plugin will impact?
> 
> @fanyangCS what is the expected behaiour for stop PAI services:

I think that is service dependent. For the plugin, it is also plugin dependent.

**Comment by yqwang-ms** [comment]
> > > We need to define whether **stop** PAI services should have impacts on running jobs.
> > > (Currently stop FC will have no impacts on exist running, but delete FC will delete running jobs)
> > > Seems current stop for device plugin will impact?
> > 
> > 
> > @fanyangCS what is the expected behaiour for stop PAI services:
> 
> I think that is service dependent. For the plugin, it is also plugin dependent.

So If any PAI service stop.sh that cause running job killed, when user stop the PAI, all jobs will be impacted. I think all PAI services should reach a consensus for this if we do not want stop PAI to impact user jobs.

**Pull request merged**
