### PR TITLE
Add guaranteed resources for low priority cluster

### PR DESCRIPTION
**Pull request by abuccts**
Add guaranteed resources for low priotity cluster.

image

### CODE REVIEW

**Comment by yqwang-ms** [comment]
Can we show the total bad nodes / cpus of each gputype?

And in current PR, all VC's guarrentee will be deducted by total bad nodes / cpus, in each gputype-wised?

Such as:
VC A contains 1 M60 and 9 K80 nodes
VC B contains 9 M60 and 1 K80 nodes
And if 2 M60 and 2 K80 nodes are dead, VC A should only be deducted by 1 (M60) + 2 (K80), i.e. 10 - 1 - 2 instead of 10 - 2 - 2.

**Comment by abuccts** [comment]
> Can we show the total bad nodes / cpus of each gputype?
> 

it's a separate feature and needs UI design, won't be added in this PR

> And in current PR, will all VC's guarrentee be deducted by total bad nodes / cpus, in each gputype-wised?
> Such as:
> VC A contains 1 M60 and 9 K80 nodes
> VC B contains 9 M60 and 1 K80 nodes
> And if 2 M60 and 2 K80 nodes are dead, VC A should only be deducted by 1 (M60) + 2 (K80), i.e. 10 - 1 - 2 instead of 10 - 2 - 2.

updated

**Comment by sunqinzheng** [comment]
I think the UI is confusing. Has the UI design reviewed by designer?

**Comment by abuccts** [comment]
> I think the UI is confusing. Has the UI design reviewed by designer?

reference #3836

**Comment by Binyang2014** [comment]
Please check with @yangou1988 , maybe he has some comments

**Comment by fanyangCS** [comment]
You can merge the PR and fix the UI in next release

**Comment by abuccts** [comment]
Transferred in #3940

**Pull request closed without merging**
