### PR TITLE
Refine home page and sign-in page

### LINKED ISSUE #3712: refine index page
Before:

image

After
L: 1920x1080px
image

M: 1366x768px
image

S:320x568px
image

### LINKED ISSUE #4074: Refine Web UI Homepage (normal user and admin) + fix no available node
Refine homepage UI
1. home page - normal user
Update the margin and padding
Add My favorite job
Homepage Normal uesr– 1920x1080px – 1
Homepage Normal user  – no available node + add my Favorite jobs 1920x1080px – 2

2. home page - admin user
Update the margin and padding
Add My recent job
Homepage admin – no available node + add my recent jobs 1920x1080px – 1
Homepage Admin – 1920x1080px

3. UI of no available GPU nodes
Show a sentence: No available GPU nodes now at the middle of the chart
image

4. Update the color of Utilization 
Usage color: 0.0 - 0.9 Green, above 0.9 Red
image

5. Fix and keep the icons of Job state align with Job list.
image

### PR DESCRIPTION
**Pull request by debuggy**
image
image
image

closes #4074 
closes #3712

### CODE REVIEW

**Comment by yangou1988** [comment]
image
1. The color of font should be blue, not purple
2. There is a box and shadow in the job list


image
1. Keep the same distance of margin
2. Change the title to "Use VS Code Extension"
3. Add an arrow icon behind the "learn more“

**Comment by abuccts** [comment]
BTW, could you confirm the home page bug #4031 is fixed in this refine?
The issue also exists in one screen of low resolution, you can reproduce it by resizing browser window.

**Comment by debuggy** [comment]
Updated sign in page:
image
image

**Comment by debuggy** [comment]
> 
> 
> BTW, could you confirm the home page bug #4031 is fixed in this refine?
> The issue also exists in one screen of low resolution, you can reproduce it by resizing browser window.

this bug has been fixed

**Pull request merged**
