### PR TITLE
Add hdfs datanode replace policy

### PR DESCRIPTION
**Pull request by mzmssg**
#1857

### CODE REVIEW

**Comment by sterowang** [comment]
>   <value>2</value>

Is the default replication set to 2 too small? 3 should be a more frequently selected configuration to balance between better data avaliability and space utilization.

---
Refers to: src/hadoop-data-node/deploy/hadoop-data-node-configuration/hdfs-site.xml:23 in d53c6c9. [](commit_id = d53c6c9200356f323b8c68de71f80e1e40199abb, deletion_comment = False)

**Comment by mzmssg** [comment]
@sterowang 
Do you mean we merge 4 configurations(RM, NM, NN, DN) into 1? 

For the replication number, I noticed we kept it for a long time.  I guess there might be some historical reasons to reduce it?

**Comment by mzmssg** [comment]
@sterowang 
For merge configuration, I think we could create a new PR for it. Then focus on datanode replace policy in current thread.

**Comment by YanjieGao** [comment]
This is client side config, how could user get and use this config? From configmap?

**Comment by mzmssg** [comment]
@YanjieGao 
Node manager will copy its configuration to user's container. Currently, spark example use this way to access YARN.

**Pull request merged**
