### PR TITLE
[Rest Server] Update hived resource validation

### PR DESCRIPTION
**Pull request by abuccts**
Update hived resource validation.

### CODE REVIEW

**Comment by mzmssg** [comment]
Maybe we can remove one from `memory`/`memoryMB` to uniform the variable name? 

@abuccts your opinion?

**Comment by mzmssg** [comment]
Actually it's the same issue as #3595. A uniform name could resolve the problem.

**Comment by abuccts** [comment]
> Actually it's the same issue as #3595. A uniform name could resolve the problem.

It's a **bug fix** instead of uniforming name.
In #3225, the source object only uses `memory` but reference uses both `memory` and `memoryMB`.

**Comment by mzmssg** [comment]
Yeah, I know it's a bug. 
I just suggest to replace all `xxMemoryMB` with `xxMemory`, then variable name align with the source.

**Pull request merged**
