### PR TITLE
increase node cpu alerting level

### PR DESCRIPTION
**Pull request by xudifsd**
increase to 90%

### CODE REVIEW

**Comment by fanyangCS** [comment]
since the system is relatively more robust to high CPU usage, we can increase the alert level of CPU to higher value.

**Comment by fanyangCS** [comment]
Also, please think of how to provide a severity level for each alert.

**Comment by xudifsd** [comment]
We can add label `severity: critical` to the alerts that we think important.

But I think this is only useful when we have other notification methods so that we can decide what notification get pushed. For example, we may add slack notification for alerts not so important, and only send out email when some critical events happened. If no other endpoints included, I see no needs to label severity level.

**Comment by fanyangCS** [comment]
@xudifsd , we can do that after we have severity levels.

**Pull request merged**
