### PR TITLE
Refine gpu chart

### LINKED ISSUE #4327: The description for X-axis is not clear and not visual optimized
there are user feedback, that the current X-axis is confusing. 

We could add one link to describe the chart and make the X-axis label simple.
i.e. description: 
The chart is to show the distribution of nodes of available GPU in nodes. 
X axis represents nodes where the number of available GPUs is X
Y axis represents the amount of the nodes

X-axis' label can be simplified to 1, 2, 3

When there are no nodes with available GPU, we should not keep the chart empty, which seems weird, we should add one nodes there saying: "No node has a GPU available.". 

image

### PR DESCRIPTION
**Pull request by debuggy**
closes #4327

image

### CODE REVIEW

**Comment by scarlett2018** [comment]
Adding @qfyin and @sunqinzheng for code review, I'm okey with the design, thanks =).

**Comment by debuggy** [comment]
update: 
image

**Comment by debuggy** [comment]
@scarlett could you help to rename the axis label to be more clear to users?

**Comment by scarlett2018** [comment]
@debuggy - how do you think the proposal by @yangou1988 ?
https://github.com/microsoft/pai/issues/4327#issuecomment-612902332

**Comment by debuggy** [comment]
> 
> 
> @debuggy - how do you think the proposal by @yangou1988 ?
> [#4327 (comment)](https://github.com/microsoft/pai/issues/4327#issuecomment-612902332)

For me, the ```Number of available GPUs``` is kind of confusing. However I am ok if you both think reasonable.

**Comment by scarlett2018** [comment]
> > @debuggy - how do you think the proposal by @yangou1988 ?
> > [#4327 (comment)](https://github.com/microsoft/pai/issues/4327#issuecomment-612902332)
> 
> For me, the `Number of available GPUs` is kind of confusing. However I am ok if you both think reasonable. @scarlett2018 @yangou1988

@debuggy - how about "Number of available GPUs on the node"? accurate enough? is that too long?

**Comment by debuggy** [comment]
> 
> 
> > > @debuggy - how do you think the proposal by @yangou1988 ?
> > > [#4327 (comment)](https://github.com/microsoft/pai/issues/4327#issuecomment-612902332)
> > 
> > 
> > For me, the `Number of available GPUs` is kind of confusing. However I am ok if you both think reasonable. @scarlett2018 @yangou1988
> 
> @debuggy - how about "Number of available GPUs on the node"? accurate enough? is that too long?

Better for me, here is the update:
image

**Pull request merged**
