### PR TITLE
[Launcher]: Add more info into SummarizedFrameworkInfo

### PR DESCRIPTION
**Pull request by yqwang-ms**
1. Add more info into SummarizedFrameworkInfo
https://github.com/Microsoft/pai/issues/2228

2. Skip to stop ZKStore in case it is still using
https://github.com/Microsoft/pai/pull/2408

### CODE REVIEW

**Comment by yqwang-ms** [comment]
Example:
image

**Comment by mzmssg** [comment]
We only provide total GPU number, without cpu or memory?

**Comment by yqwang-ms** [comment]
Good point, let me added it.

**Comment by mzmssg** [comment]
@yqwang-ms 
Another question, will it count AM resource

**Comment by yqwang-ms** [comment]
It seems not easy to judge this. So, let's only add current fields, the memory and cpu is TBD in future release.

**Pull request merged**
